Animal
fisher60/Friendo_Bot pull request #153
Opened 2020-11-20 22:38 UTC by mcurranseijo

Adding animal cog

2020-11-20 23:44 UTC, fisher60 requested changes
please remove the weather cog from this pr. In the future, you need to do:
```
git checkout develop
git pull
git checkout -b my/branch-name
```
so that you checkout and branch from develop, rather than branching from a branch you were working on.

It is also important to run `git status` before committing.  This would have shown you that you were adding files from another branch.

2020-11-21 19:08 UTC, fisher60 requested changes
Overall this looks really good, a few things need to be changed. I would like to start only using the bot's session, rather than aiohttp sessions. This is something I only learned to do recently.

2020-11-21 19:08 UTC, fisher60 commented on bot/cogs/animals.py
> +        await self.animal_fact(ctx, url, fact_url, 'Bird')
we can add plurals to the aliases, i.e `cats` or `pandas` so that users are more likely to guess the correct command.

2020-11-21 19:08 UTC, fisher60 commented on bot/cogs/animals.py
> +                fact = (await resp.json())['fact']
needs line breaks
```suggestion
        async with aiohttp.ClientSession() as session:
            if animal == 'cat':
                async with session.get(url) as resp:
                    data = (await resp.json())[0]['url']      
            else:
                async with session.get(url) as resp:
                    data = (await resp.json())['link']
                    
            async with session.get(fact_url) as resp:
                fact = (await resp.json())['fact']
```
something like that

2020-11-21 19:08 UTC, fisher60 commented on bot/cogs/animals.py
> +from discord.ext import commands
you should import what you need `from discord.ext.commands`
```suggestion
from discord.ext.commands import Cog, command, bot
```
then change the rest of the file to match this change

2020-11-24 18:38 UTC, Xithrius commented
When hitting "commit changes", please edit the message so the commit message describes what you're doing. 

"Update animals.py" doesn't tell the reader anything.

2020-11-26 00:45 UTC, fisher60 requested changes
overall this looks really good and it ran very well. I have a few warning from my IDE for some simple things. I recommend removing the `bot` import and replacing it with `Bot`

It could also help to import `Friendo` for the type hints, this will allow for more accurate hints from an IDE.

2020-11-26 00:45 UTC, fisher60 commented on bot/cogs/animals.py
> +from discord.ext.commands import Cog, bot, command, context
you should import `Bot` here, instead of bot, this will solve multiple issues that will be outlined below.

2020-11-26 00:45 UTC, fisher60 commented on bot/cogs/animals.py
> +        self.bot = bot
`bot` is used three different ways here, if we correct the import, then we can use `bot: Bot` instead. Or better yet, we can import `Friendo` from `bot.bot` and do `def __init__(self, bot: Friendo):`

2020-11-26 00:45 UTC, fisher60 commented on bot/cogs/animals.py
> +        async with self.bot.session.get(url) as url:
if we are using `Friendo` in the type hints, this problem will be fixed, but my IDE is trying to find a reference for `session` in the wrong place it appears.

2020-11-26 00:45 UTC, fisher60 commented on bot/cogs/animals.py
> +def setup(bot: bot.Bot) -> None:
this also gives a warning, since we are importing `bot`, this overwrites `bot` from the outer context.

2020-12-14 07:16 UTC, fisher60 commented
@mcurranseijo let me know if you are still interested in finishing this feature

2021-05-25 02:10 UTC, closed without merging