AoC 2020 commands
fisher60/Friendo_Bot pull request #163
Opened 2020-12-02 16:45 UTC by saiTama-max

Added  2 commands for Code Collective server for AoC 2020, join (to join the Code Collective leaderboard) and leaderboard (to view the leaderboard)

2020-12-02 20:28 UTC, fisher60 commented
@saiTama-max do we want multiple servers to be able to join our personal leaderboard though?

2020-12-03 03:59 UTC, saiTama-max commented
@fisher60 i was thinking about that, in some cases it could be good for more competition, but if the server doesn't agree then i could remove it

2020-12-03 07:47 UTC, fisher60 requested changes
overall this looks great. just some quick, small fixes to finish it up.

2020-12-03 07:47 UTC, fisher60 commented on bot/cogs/advent_of_code.py
> +    @group(name="adventofcode", aliases=('aoc', 'aoc2020'))
missing `brief`, causes help command to error

2020-12-03 07:47 UTC, fisher60 commented on bot/cogs/advent_of_code.py
> +                       usage=".join",
usage incorrect, correct usage is `.aoc join`

2020-12-03 07:47 UTC, fisher60 commented on bot/cogs/advent_of_code.py
> +                       usage=".leaderboard",
usage should be `.aoc leaderboard`

2020-12-05 12:56 UTC, saiTama-max commented
uh i just realized theres a bug in the rendering, its mismatched when the star cont is 2 digit now, i will fix that soon

2020-12-05 21:01 UTC, fisher60 approved these changes
This looks great, runs perfect, ty.

2020-12-05 21:01 UTC, merged