Fixed padding for AoC leaderboard
fisher60/Friendo_Bot pull request #169
Opened 2020-12-06 15:42 UTC by saiTama-max

Now the lines are equally spaced, also added a horizontal line separating the headers

2020-12-11 01:36 UTC, fisher60 requested changes
I cannot approve this, it contains changes from another branch, consider rebasing/fixing this branch so we can continue with the PR.

2020-12-14 07:23 UTC, Xithrius requested changes

2020-12-14 07:23 UTC, Xithrius commented on bot/cogs/utilities.py
> +            final.append(f'{years} years')
I think most of this could be turned into a for loop that cheks items of a list.

2020-12-14 07:23 UTC, Xithrius commented on bot/cogs/utilities.py
> +import datetime
```suggestion
from datetime import datetime
```
You only use `datetime.datetime` for `utcnow()`, I don't think adding an extra layer is necessary.

2020-12-14 07:23 UTC, Xithrius commented on bot/cogs/utilities.py
> +                           inline=False)
You can combine all add_field calls into a for loop. The information would be stored in a dictionary for ease of editibility in the future.
```suggestion
        user_info = {
                'User Information': f'Created: {create_time} ago\nProfile: {men}\nID: {id_}\n{is_bot}',
                'Guild Profile': f'Joined: {joined_time} ago\nNick: {nick}\nRoles: {roles}',
                'Status': statuses,
                'Activity': activity
       }
       for k, v in user_info.items():
                info_emb.add_field(name=k, value=v, inline=False)
```

2020-12-14 07:23 UTC, Xithrius commented on bot/cogs/utilities.py
> +          'early_supporter': '<:early:784756624509108224>'}
Probably could go into some constants/config (yaml) file.

2020-12-20 04:51 UTC, Xithrius commented
Discussion will continue in PR #178

2020-12-20 04:51 UTC, closed without merging