fixes 183
fisher60/Friendo_Bot pull request #189
Opened 2021-04-11 05:44 UTC by MS-Ignis

added default arguments and changed name of variable n to quantity

2021-05-08 18:38 UTC, GDWR commented
There is an issue with this change. 
You have changed the parameters to the command, but not changed the code to recreate the functionality.

`n is not defined`

```py
  @command(
      brief="simulates a dice roll",
      description=".dice [quantity] [sides]\n"
                  "`quantity` - how many to roll\n"
                  "`sides` - how many sides each die will have",
  )
  async def dice(self, ctx: Context, quantity: int = 1, sides: int = 6) -> None:
      """Simply rolling a die."""
      if n <= 0:
          await ctx.send("you must roll at least one die")
      elif sides < 2:
          await ctx.send(f"you can't roll a {sides}-sided die")
      else:
          result = sum(randint(1, sides) for _ in range(n)) # n is not defined

          await ctx.send(f"you rolled {result}")
```

2021-05-08 18:40 UTC, GDWR requested changes

2021-05-08 18:40 UTC, GDWR commented on bot/cogs/fun.py
> +    async def dice(self, ctx: Context, quantity: int = 1, sides: int = 6) -> None:
You have changed the parameters of this command, but the code block still is using the previous command signature

`n is not defined`

2021-06-12 06:54 UTC, fisher60 commented
Stale, closing. Feel free to open again.

2021-06-12 06:54 UTC, closed without merging